-- Generated by scripts/generate-seed.mjs. Do not edit by hand.
begin;

insert into public.words (text, ipa, pos) values
('two', '/tuː/', 'numeral'),
('bags', '/bægz/', 'noun'),
('have', '/hæv/', 'verb'),
('a', '/ə/', 'article'),
('red', '/rɛd/', 'adjective'),
('car', '/kɑːr/', 'noun'),
('we', '/wiː/', 'pronoun'),
('dream', '/driːm/', 'noun'),
('she', '/ʃiː/', 'pronoun'),
('reads', '/riːdz/', 'verb'),
('every', '/ˈɛvri/', 'adjective'),
('day', '/deɪ/', 'noun'),
('I', '/aɪ/', 'pronoun'),
('like', '/laɪk/', 'verb'),
('black', '/blæk/', 'adjective'),
('coffee', '/ˈkɔːfi/', 'noun'),
('the', '/ðə/', 'article'),
('cat', '/kæt/', 'noun'),
('is', '/ɪz/', 'verb'),
('on', '/ɑːn/', 'preposition'),
('table', '/ˈteɪbəl/', 'noun'),
('they', '/ðeɪ/', 'pronoun'),
('walk', '/wɔːk/', 'verb'),
('to', '/tuː/', 'preposition'),
('school', '/skuːl/', 'noun'),
('are', '/ɑːr/', 'verb'),
('very', '/ˈvɛri/', 'adverb'),
('happy', '/ˈhæpi/', 'adjective'),
('today', '/təˈdeɪ/', 'adverb'),
('please', '/pliːz/', 'adverb'),
('open', '/ˈoʊpən/', 'verb'),
('window', '/ˈwɪndoʊ/', 'noun')
on conflict (text, pos) do update set ipa = excluded.ipa;

insert into public.phrases (text, translation, level, kind, sort_order, audio_path) values
('two bags', 'duas bolsas', 1, 'phrase', 1, '/audio/two-bags.mp3'),
('have two bags', 'ter duas bolsas', 1, 'phrase', 2, '/audio/have-two-bags.mp3'),
('a red car', 'um carro vermelho', 1, 'phrase', 3, '/audio/a-red-car.mp3'),
('we have a dream', 'nós temos um sonho', 2, 'sentence', 4, '/audio/we-have-a-dream.mp3'),
('she reads every day', 'ela lê todos os dias', 2, 'sentence', 5, '/audio/she-reads-every-day.mp3'),
('I like black coffee', 'eu gosto de café puro', 2, 'sentence', 6, '/audio/i-like-black-coffee.mp3'),
('the cat is on the table', 'o gato está na mesa', 3, 'sentence', 7, '/audio/the-cat-is-on-the-table.mp3'),
('they walk to school', 'eles caminham para a escola', 2, 'sentence', 8, '/audio/they-walk-to-school.mp3'),
('we are very happy today', 'estamos muito felizes hoje', 3, 'sentence', 9, '/audio/we-are-very-happy-today.mp3'),
('please open the window', 'por favor, abra a janela', 2, 'sentence', 10, '/audio/please-open-the-window.mp3')
on conflict (text) do update set
  translation = excluded.translation,
  level       = excluded.level,
  kind        = excluded.kind,
  sort_order  = excluded.sort_order,
  audio_path  = excluded.audio_path;

insert into public.phrase_words (phrase_id, word_index, word_id)
select p.id, v.word_index, w.id
from (values
('two bags', 0, 'two', 'numeral'),
('two bags', 1, 'bags', 'noun'),
('have two bags', 0, 'have', 'verb'),
('have two bags', 1, 'two', 'numeral'),
('have two bags', 2, 'bags', 'noun'),
('a red car', 0, 'a', 'article'),
('a red car', 1, 'red', 'adjective'),
('a red car', 2, 'car', 'noun'),
('we have a dream', 0, 'we', 'pronoun'),
('we have a dream', 1, 'have', 'verb'),
('we have a dream', 2, 'a', 'article'),
('we have a dream', 3, 'dream', 'noun'),
('she reads every day', 0, 'she', 'pronoun'),
('she reads every day', 1, 'reads', 'verb'),
('she reads every day', 2, 'every', 'adjective'),
('she reads every day', 3, 'day', 'noun'),
('I like black coffee', 0, 'I', 'pronoun'),
('I like black coffee', 1, 'like', 'verb'),
('I like black coffee', 2, 'black', 'adjective'),
('I like black coffee', 3, 'coffee', 'noun'),
('the cat is on the table', 0, 'the', 'article'),
('the cat is on the table', 1, 'cat', 'noun'),
('the cat is on the table', 2, 'is', 'verb'),
('the cat is on the table', 3, 'on', 'preposition'),
('the cat is on the table', 4, 'the', 'article'),
('the cat is on the table', 5, 'table', 'noun'),
('they walk to school', 0, 'they', 'pronoun'),
('they walk to school', 1, 'walk', 'verb'),
('they walk to school', 2, 'to', 'preposition'),
('they walk to school', 3, 'school', 'noun'),
('we are very happy today', 0, 'we', 'pronoun'),
('we are very happy today', 1, 'are', 'verb'),
('we are very happy today', 2, 'very', 'adverb'),
('we are very happy today', 3, 'happy', 'adjective'),
('we are very happy today', 4, 'today', 'adverb'),
('please open the window', 0, 'please', 'adverb'),
('please open the window', 1, 'open', 'verb'),
('please open the window', 2, 'the', 'article'),
('please open the window', 3, 'window', 'noun')
) as v(phrase, word_index, word, pos)
join public.phrases p on p.text = v.phrase
join public.words   w on w.text = v.word and w.pos = v.pos
on conflict (phrase_id, word_index) do update set word_id = excluded.word_id;

commit;
