// Generates supabase/seed.sql from src/lib/exercises.ts, so code and database share one source.
//   node --experimental-strip-types scripts/generate-seed.mjs
// Run the resulting file in the Supabase SQL Editor (safe to re-run: it upserts).
import { writeFileSync } from "node:fs";
import { EXERCISES, sentenceOf } from "../src/lib/exercises.ts";
import { audioPath } from "../src/lib/audio-slug.ts";

const q = (s) => `'${String(s).replaceAll("'", "''")}'`;

const texts = EXERCISES.map(sentenceOf);
const dup = texts.find((t, i) => texts.indexOf(t) !== i);
if (dup) throw new Error(`duplicate phrase: "${dup}"`);

const words = new Map();
const links = [];
const phrases = EXERCISES.map((e, i) => {
  const text = sentenceOf(e);
  e.words.forEach((w, pos) => {
    words.set(`${w.text}|${w.pos}`, w);
    links.push(`(${q(text)}, ${pos}, ${q(w.text)}, ${q(w.pos)})`);
  });
  const n = e.words.length;
  const kind = n === 1 ? "word" : n <= 3 ? "phrase" : "sentence";
  const level = n <= 3 ? 1 : n === 4 ? 2 : 3;
  return `(${q(text)}, ${q(e.translation)}, ${level}, ${q(kind)}, ${i + 1}, ${q(audioPath(text))}, ${q(e.planet)})`;
});

const wordRows = [...words.values()].map((w) => `(${q(w.text)}, ${q(w.ipa)}, ${q(w.pos)})`);

const sql = `-- Generated by scripts/generate-seed.mjs. Do not edit by hand.
begin;

insert into public.words (text, ipa, pos) values
${wordRows.join(",\n")}
on conflict (text, pos) do update set ipa = excluded.ipa;

insert into public.phrases (text, translation, level, kind, sort_order, audio_path, planet) values
${phrases.join(",\n")}
on conflict (text) do update set
  translation = excluded.translation,
  level       = excluded.level,
  kind        = excluded.kind,
  sort_order  = excluded.sort_order,
  audio_path  = excluded.audio_path,
  planet      = excluded.planet;

insert into public.phrase_words (phrase_id, word_index, word_id)
select p.id, v.word_index, w.id
from (values
${links.join(",\n")}
) as v(phrase, word_index, word, pos)
join public.phrases p on p.text = v.phrase
join public.words   w on w.text = v.word and w.pos = v.pos
on conflict (phrase_id, word_index) do update set word_id = excluded.word_id;

commit;
`;
writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql);
console.log(`seed.sql: ${words.size} words, ${phrases.length} phrases, ${links.length} links`);
